version: '3.5'
services:
  postgres:
    image: postgres:12
    environment:
      DA_CLI: psql -U ${USER} -d ${USER}_dev
      PGDATA: /pgtmpfs
      POSTGRES_DB: ${USER}
      POSTGRES_USER: ${USER}
      POSTGRES_MULTIPLE_DATABASES: ${USER}_dev,${USER}_test
      POSTGRES_HOST_AUTH_METHOD: trust
    tmpfs:
    - /pgtmpfs
    volumes:
    - ~/da/.da-home:/root:rw
    - ~/da/resources/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
  long_service:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    command: tail -f /dev/null
    environment:
      DB_NAME: ${USER}_dev
      DB_USER: ${USER}
      DA_CLI: bash
    volumes:
    - ~/.da/.da-home:/root:rw
    - ~/.aws/credentials:/root/.aws/credentials:rw
  something_else:
    environment:
      DA_CLI: bash
    volumes:
    - ~/.da/.da-home:/root:rw
